#!/bin/sh

echo "-----Fixing FontForge debris and normalizing UFOs..."
psffixffglifs source/masters/EastSyriacMarcusNew-Regular.ufo -p checkfix=fix     &
wait

# Continue with normal preflight
./preflight
