#!/bin/sh

echo "-----Normalizing Regular UFO..."
echo "-----Updating production names in Regular..."
psfsetpsnames -q -p checkfix=none -i source/glyph_data.csv source/masters/Ramsina-Regular.ufo

echo "-----Updating glyph orders in Regular..."
psfsetglyphorder -q --header sort_final -i source/glyph_data.csv source/masters/Ramsina-Regular.ufo -p backup=False -x

echo "-----Normalizing other UFOs..."
psfnormalize -p checkfix=fix source/masters/Ramsina-Regular.ufo       &
wait

echo "-----Syncing glyph orders, psnames, and other metadata to other UFOs..."
psfsyncmasters -q source/Ramsina.designspace 

echo "Updating woff metadata files..."
psfmakewoffmetadata -q -n  Ramsina        -i org.sil.fonts source/masters/*-Regular.ufo  -o "source/Ramsina-WOFF-metadata.xml"

echo "Building internal fea..."
makefea -o source/masters/Ramsina-Regular.ufo/features.fea --ignoreglyphs -l source/logs/Ramsina-Regular-psfmakefea.log -i source/opentype/main.feax --omitaps "R, O, L" source/masters/Ramsina-Regular.ufo &

wait

echo "-----Preflight completed!"
